### ISSUE TITLE
Broken textures after using vertexbuffer

### ISSUE THREAD

**Issue by Nathan-M-code** [Zombieschannel/SFML#6]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

No error message.
All sfml sprites are white after drawing sf::VertexBuffer, but the vertexbuffer itself is drawn.
After replacing VertexBuffer for VertexArray, everything is normal again.
I absolutely don't have a clue of what might be the problem. I checked the texture pointer of each sprites and I seemed ok. I didn't to dive into the sfml code.

It doesnt affect me much, as using vertexarray is also good to me. Just want to let you know.

### Your Environment

- OS / distro / window manager: Android arm64 v8a
- SFML version: GLES2 branch (btw which one must be used ?)
- Compiler / toolchain: ndk-26d

### Steps to reproduce

```cpp
Sorry I dont have much time right now, I'll make one if you absolutely need one
```

### Expected behavior

normal sprite drawing

### Actual behavior

white sprites

**Comment by Zombieschannel** [comment]
I'll look into it at some point, as I too don't have much time atm.
Is it only Sprite + VertexBuffer? Since I know I mix RectangleShape and VertexBuffer in my game which uses this branch and everything works fine.
Also, I renamed this GLES2 branch to SFML-2.6.x-GLES2 as it is SFML 2.

And technically, I use the now-called SFML-2.6.x-GLES2-FixedResolutions which has one additional commit over SFML-2.6.x-GLES2 and it just makes VideoMode::getDesktopMode() on Android return full device screen resolution compared to how SFML does it currently which returns a slightly smaller resolution on devices with a hole punch/notch and then a Event::Resize happens at some point in the beginning which makes my life more difficult. Other than that, these 2 branches are identical.

**Comment by Zombieschannel** [comment]
Yup, that is strange, probably something wrong with the default nontexture shader considering that if you add a texture to the vertex buffer it works fine `if(vbDrawn) window.draw(vb, &t);`

Will check what is up with that, thanks for reporting!
